// this is the global template layout that will be applied to all the pages in (pages)/ folder

import "./globals.css";
import { cn } from "@/lib/utils";
import { poppins } from "@/lib/fonts";
import Navbar from "@/components/Navbar";
import "react-loading-skeleton/dist/skeleton.css";
import { Toaster } from "@/components/ui/toaster";


export const metadata = {
  title: { default: "Open Stack", template: "%s | Open Stack" },
  description: "Generated by Arjun MS",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen font-sans antialiased bg-white",
          poppins.className
        )}
      >
        <Navbar />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
